const ACTIONS = {
  FETCHING_PRODUCTS_SUCCESS: 'FETCHING_PRODUCTS_SUCCESS',
  FETCHING_PRODUCTS_FAILURE: 'FETCHING_PRODUCTS_FAILURE',
  FETCHING_CATEGORIES_SUCCESS: 'FETCHING_CATEGORIES_SUCCESS',
  FETCHING_CATEGORIES_FAILURE: 'FETCHING_CATEGORIES_FAILURE',
  FETCHING_COLLECTIONS_SUCCESS: 'FETCHING_COLLECTIONS_SUCCESS',
  FETCHING_COLLECTIONS_FAILURE: 'FETCHING_COLLECTIONS_FAILURE',
};

export default ACTIONS;
