const ACTIONS = {
  FETCHING_PRODUCTS_SUCCESS: 'FETCHING_PRODUCTS_SUCCESS',
  FETCHING_PRODUCTS_FAILURE: 'FETCHING_PRODUCTS_FAILURE',
  FETCHING_CATEGORIES_SUCCESS: 'FETCHING_CATEGORIES_SUCCESS',
  FETCHING_CATEGORIES_FAILURE: 'FETCHING_CATEGORIES_FAILURE',
  FETCHING_COLLECTIONS_SUCCESS: 'FETCHING_COLLECTIONS_SUCCESS',
  FETCHING_COLLECTIONS_FAILURE: 'FETCHING_COLLECTIONS_FAILURE',
  SET_CART_PRODUCTS: 'SET_CART_PRODUCTS',
  GET_CART_PRODUCTS: 'GET_CART_PRODUCTS',
  REMOVE_CART_BY_ID_PRODUCTS: 'REMOVE_CART_BY_ID_PRODUCTS',
  FETCHING_ORDERS_SUCCESS: 'FETCHING_ORDERS_SUCCESS',
  FETCHING_ORDERS_FAILURE: 'FETCHING_ORDERS_FAILURE',
  SET_ORDERS_SUCCESS: 'SET_ORDERS_SUCCESS',
  SET_ORDERS_FAILURE: 'SET_ORDERS_FAILURE',
};

export default ACTIONS;
